import { FormEvent, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useShop } from '../context/ShopContext'
import { money } from '../components/ProductCard'
export default function CheckoutPage(){
 const {cart,cartTotal,createOrder}=useShop(); const nav=useNavigate(); const [busy,setBusy]=useState(false); const [payment,setPayment]=useState<'card'|'cod'>('card'); const [delivery,setDelivery]=useState('Нова пошта · відділення')
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault(); if(!cart.length)return; setBusy(true); const f=new FormData(e.currentTarget); try{const order=await createOrder({items:cart,total:cartTotal,payment,customer:{name:String(f.get('name')||''),phone:String(f.get('phone')||''),email:String(f.get('email')||''),city:String(f.get('city')||''),delivery,address:String(f.get('address')||''),comment:String(f.get('comment')||'')}}); if(payment==='card'&&import.meta.env.VITE_PAYMENT_ENDPOINT){const response=await fetch(import.meta.env.VITE_PAYMENT_ENDPOINT,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({orderId:order.id,total:order.total})}); if(response.ok){const data=await response.json().catch(()=>({})); if(data?.redirectUrl){window.location.href=data.redirectUrl; return}}} nav(`/success/${order.id}`)}finally{setBusy(false)}}
 return <section className="checkout"><div><span className="eyebrow">CHECKOUT / SECURE</span><h1>Оформлення<br/><em>без зайвого.</em></h1><p>Залиште контакти, оберіть доставку та оплату. Після оформлення менеджер може підтвердити деталі.</p></div><form onSubmit={submit}><div className="form-block"><h2>01 · Контакти</h2><div className="form-grid"><label>Імʼя<input required name="name"/></label><label>Телефон<input required name="phone"/></label><label>Email<input type="email" name="email"/></label><label>Місто<input required name="city"/></label></div></div><div className="form-block"><h2>02 · Доставка</h2><div className="choice-row">{['Нова пошта · відділення','Нова пошта · курʼєр'].map(x=><button type="button" className={delivery===x?'active':''} onClick={()=>setDelivery(x)} key={x}>{x}</button>)}</div><label>Відділення / адреса<input required name="address"/></label></div><div className="form-block"><h2>03 · Оплата</h2><div className="choice-row"><button type="button" className={payment==='card'?'active':''} onClick={()=>setPayment('card')}>Карткою онлайн</button><button type="button" className={payment==='cod'?'active':''} onClick={()=>setPayment('cod')}>При отриманні</button></div><label>Коментар<textarea name="comment" rows={4}/></label></div><div className="checkout-total"><span>До сплати</span><strong>{money(cartTotal)}</strong><button disabled={busy||!cart.length} className="cta-solid">{busy?'Створюємо…':'Підтвердити замовлення'}</button></div></form></section>
}
